---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  require_chef_omnibus: 12
  name: chef_zero

platforms:
  - name: amazonlinux
    driver_config:
      image: amazonlinux
      platform: rhel
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
      - recipe[test::bashrc_manager]
